# Generated by Django 5.1.3 on 2024-12-25 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='food_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.fooditem'),
            preserve_default=False,
        ),
    ]
