# Generated by Django 5.1.3 on 2024-12-29 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_quantity'),
        ('food', '0002_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'food_item')},
        ),
    ]
