# Generated by Django 5.1.3 on 2024-12-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order_discount_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mobile Banking', 'Mobile Banking')], default='Cash', max_length=20),
        ),
    ]
